name: ftp upload
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: SamKirkland/FTP-Deploy-Action@2.0.0
      - name: Use Node.js 12.13
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Project
        run: |
          yarn
          yarn build

        env:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_ACCOUNT }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: /curation-eat-ky/dist
          git-ftp-args: --remote-root /
          ARGS: --delete
